apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-exp
  template:
    metadata:
      labels:
        app: mongo-exp
    spec:
      containers:
      - name: mongoexp
        image: mongo-express
        ports:
        - containerPort: 8081
        env: # need to revise completely
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_INITDB_ROOT_PASSWORD
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongodb-internal-service
          - name: ME_CONFIG_MONGODB_URL
            value: mongodb://mongodb-internal-service:27017
          - name: ME_CONFIG_BASICAUTH_USERNAME
            value: admin
          - name: ME_CONFIG_BASICAUTH_PASSWORD
            value: pass
---
kind: Service #to expose the mongo-express #external service
apiVersion: v1
metadata:
  name: mongodb-exp-service
spec:
  selector:
    app: mongo-exp #label of the pod
  type:  LoadBalancer
  ports:
  - protocol: TCP
    port:  8081 #service port
    targetPort:  8081 #containerport
    nodePort: 30000 # from which port we can access it from
