apiVersion: apps/v1
kind: Deployment
metadata: #deployment
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  mongodb #using label of the pod
  template: #pod 
    metadata:
      labels:
        app:  mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME #environment variable
            valueFrom:
              secretKeyRef:
                name:  mongodb-secret #name of the secret not the file name of the secret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  mongodb-secret
                key: MONGO_INITDB_ROOT_PASSWORD
---
kind: Service
apiVersion: v1
metadata:
  name:  mongodb-internal-service
spec:
  selector:
    app: mongodb #label of the pod
  #type:  LoadBalancer | ClusterIP | NodePort having some doubts
  ports:
  - name: internal
    protocol: TCP
    port:  27017 #service port
    targetPort:  27017 #containerport
            


